[platformio]
default_envs = esp_b

[env]
platform = espressif32@6.12.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
monitor_eol = LF
monitor_echo = yes
monitor_filters = send_on_enter, log2file
build_flags = -DCONFIG_MBEDTLS_HKDF_C
build_src_filter = +<main.cpp> +<wireless_driver.cpp>

[env:esp_a]
build_flags = -DCONFIG_MBEDTLS_HKDF_C -DDEVICE_ROLE=1

[env:esp_b]
build_flags = -DCONFIG_MBEDTLS_HKDF_C -DDEVICE_ROLE=2

[env:intruso]
build_flags = -DCONFIG_MBEDTLS_HKDF_C -DDEVICE_ROLE=1 -DDEVICE_ROGUE
